### ISSUE TITLE
Wait what happened?

### ISSUE THREAD

**Issue by Drakoflame** [SmithsModding/SmithsCore#10]
http://pastebin.com/A3ad41xG huh? I was just testing in creative, making a bunch of rings so I could make my first ever set of armor (kinda hard to tell if its working when with it, but just sitting and waiting is a good example, never knew how hard it was to make a forge... also, might I reccomend making the two ingots next to the plates the same temp, 1091, not 1256)

**Comment by marchermans** [comment]
Seems like I missed a spot for a null check, will fix.

**Comment by marchermans** [comment]
Fixed it, i had a problem with the HeatableItemRegistery. New build on the way.
