### ISSUE TITLE
not working in server mode

### ISSUE THREAD

**Issue by charchess** [SmithsModding/SmithsCore#11]
Hello, 

tried to start it in server mode on my ...server (linux/docker)... but crashed

did a fresh clean install locally (windows) and working in solo mode
did a freshc clean forge server install with only that lib and is failing

a little googling on "java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP" led me to think this mod (library) is not intended to work in server mode ? or am I missing something ?

Maybe I'm missing something ? if you need more information, feel free to ask

Charchess

**Comment by McJty** [comment]
I think this mod might not work in server mode because it uses a network channel name that is bigger then 20 characters (23) and that's not allowed. Just guessing but we're investigating a problem with this in a pack my son is making and we got this message

**Comment by McJty** [comment]
Indeed:

```
    INSTANCE = new SimpleNetworkWrapper(CoreReferences.General.MOD_ID.toLowerCase() + "-EventSyncing");
```

that's too long and will overflow the maximum of 20 characters there

**Comment by marchermans** [comment]
I am aware of that Problem. Currently this mod is in Beta and i had no time to test the new Messaging system that is part of the 1.9 / 1.10 Branch, yet. Thanks for the Report i will fix this tomorrow, when i am Home.

**Comment by marchermans** [comment]
Oke I have taken a look at this and indeed the channel name is too long. That will be fixed in the next release which will come up in about a day or so (basically once I can get on to my dev pc and off this crappy dev laptop) 

For the bug that @charchess is describing I would need the full log, I might have missed a conversion from EntityPlayerSP to MP somewhere and I need to know where. Could you upload the full log to something like gist.github.com or pastebin.com? If you can do that today I can try to fix it in the same release as the naming thing.

**Comment by charchess** [comment]
okay here is the fml-server-latest.log
http://pastebin.com/wPrydDCU
if you need anything else, feel free to ask
good luck with the debug

**Comment by marchermans** [comment]
Found both issues, tested my self today as well. SmithsCore should start in server mode now. A new version will be released in around 30 minutes when all goes well with Travis.

**Comment by thecanidcoder** [comment]
Issue does not seem to be resolved with the newest beta versions of SmithsCore and Armory. Everything starts fine in client, including in my personal 150+ mod pack; with only Armory and SmithsCore in server, it will not start.

Pastebin includes Armory-Weaponry, however a quick test without that mod yielded the same results.

http://pastebin.com/qvNe5Pt8

**Comment by marchermans** [comment]
Ah i seem to have screwed up when i updated a couple days agop. Will fix this asap.
