### ISSUE TITLE
Crashing on Startup!

### ISSUE THREAD

**Issue by Drakoflame** [SmithsModding/SmithsCore#8]
http://pastebin.com/dwu6A6KJ Dunno what's happening, or why, every time I boot up on 1.10.2, I get this crash, I tried taking out the SmithsCore, but obviously that means that Armory won't work XD

I'll just leave this here for someone to try and help, I'd love to play with this and make cool armors!

**Comment by marchermans** [comment]
I will need some time and your help to fix this, i will need to build a special version of SC that will allow you to send me additional data through the crash log.

**Comment by marchermans** [comment]
Drako i commited something to armory to bake the HeatedItems differently
I hope that this fixes it.
